# Generated by Django 4.2.5 on 2023-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="posts", to="blog.comment"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="posts",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tags", to="blog.post"
            ),
        ),
    ]
